# Generated by Django 5.1.7 on 2025-05-12 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menu_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
                ('Completed_Status', models.BooleanField(default=False)),
                ('Customer_Submitted', models.BooleanField(default=False)),
                ('Total_Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_Name', models.CharField(max_length=100, unique=True)),
                ('Table_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
                ('Menu_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletapapp.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletapapp.menu_category')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Item_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletapapp.menu_item')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletapapp.order')),
            ],
            options={
                'unique_together': {('Order_ID', 'Item_ID')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Items',
            field=models.ManyToManyField(through='tabletapapp.Order_Item', to='tabletapapp.menu_item'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Restaurant_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletapapp.restaurant'),
        ),
        migrations.AddField(
            model_name='menu',
            name='Restaurant_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletapapp.restaurant'),
        ),
        migrations.CreateModel(
            name='Restaurant_Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Owner_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletapapp.owner')),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletapapp.restaurant')),
            ],
            options={
                'unique_together': {('Owner_ID', 'Restaurant_ID')},
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Owners',
            field=models.ManyToManyField(through='tabletapapp.Restaurant_Owner', to='tabletapapp.owner'),
        ),
        migrations.AddField(
            model_name='owner',
            name='Restaurants',
            field=models.ManyToManyField(blank=True, through='tabletapapp.Restaurant_Owner', to='tabletapapp.restaurant'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_Name', models.CharField(max_length=100)),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletapapp.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Table_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletapapp.table'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Current_Order_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_customers', to='tabletapapp.order')),
                ('Last_Order_ID_Submitted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_customers', to='tabletapapp.order')),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletapapp.restaurant')),
                ('Table_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabletapapp.table')),
            ],
        ),
    ]
