# Generated by Django 5.2 on 2025-05-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabletapapp', '0002_alter_table_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Table_ID',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Table_ID',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
