# Generated by Django 5.2 on 2025-05-14 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletapapp', '0003_remove_order_table_id_remove_customer_table_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletapapp.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Table_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tabletapapp.table'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
